image: gitlab.fit.cvut.cz:5000/ict/alpine-docker-images/base:3.16

main:
    stage: test
    script:
        - apk add build-base
        - apk add boost-dev
        - make test        
        - ./test --log_level=all --result_code=no 
        
